# ─── Multi-stage build: single-container deploy (server + dashboard) ─────
# Stage 1: build the React dashboard
FROM node:26-bookworm-slim AS dashboard-build
WORKDIR /app/dashboard
COPY dashboard/package*.json ./
# Use `npm ci` for a reproducible install when a lockfile is committed; fall
# back to `npm install` for freshly generated platforms that ship none.
RUN if [ -f package-lock.json ]; then npm ci --no-audit --no-fund; else npm install --no-audit --no-fund; fi
COPY dashboard/ ./
# REACT_APP_API_URL is baked in at build time; default to /api so the
# dashboard talks to the same origin as the server.
ARG REACT_APP_API_URL=/api
ENV REACT_APP_API_URL=$REACT_APP_API_URL
RUN npm run build

# Stage 2: install server deps + prisma generate
FROM node:26-bookworm-slim AS server-build
WORKDIR /app/server
# OpenSSL is needed by Prisma's query engine on bookworm-slim; python3/make/g++
# let node-gyp compile native deps (better-sqlite3) when no prebuilt binary fits.
RUN apt-get update && apt-get install -y --no-install-recommends openssl ca-certificates curl tini python3 make g++ \
    && rm -rf /var/lib/apt/lists/*
COPY server/package*.json ./
COPY server/prisma ./prisma
# `npm ci`/`npm install` triggers `postinstall: prisma generate` (needs
# prisma/schema.prisma). Prefer the lockfile when present; fall back otherwise.
RUN if [ -f package-lock.json ]; then npm ci --no-audit --no-fund --omit=dev; else npm install --no-audit --no-fund --omit=dev; fi
COPY server/ ./
# Generate Postgres schema ahead of time so migrate deploy has it at boot.
RUN node prisma/sync-postgres-schema.js
# Replace the SQLite client generated by postinstall with the Postgres-provider
# client required in production. Local development remains SQLite.
RUN npx prisma generate --config prisma.postgres.config.ts

# Stage 3: runtime image
FROM node:26-bookworm-slim AS runtime
ENV NODE_ENV=production \
    SERVE_DASHBOARD=1 \
    PORT=8080
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends openssl ca-certificates curl tini \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd --system --gid 1001 app \
    && useradd --system --uid 1001 --gid app --home /app --shell /usr/sbin/nologin app
COPY --from=server-build    --chown=app:app /app/server            /app/server
COPY --from=dashboard-build --chown=app:app /app/dashboard/build   /app/dashboard/build
# Writable uploads dir for STORAGE_DRIVER=local (override with volume / S3)
RUN mkdir -p /app/server/uploads && chown -R app:app /app/server/uploads
USER app
WORKDIR /app/server
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD curl -fsS http://127.0.0.1:${PORT}/api/health/live || exit 1
# tini = PID 1 so SIGTERM propagates (graceful shutdown in lifecycle.js)
ENTRYPOINT ["/usr/bin/tini", "--"]
# Apply Postgres migrations at boot, then start the API. Safe to run on every
# boot — Prisma marks applied migrations. Omit `db:postgres:deploy` when using
# an external migration job.
CMD ["sh", "-c", "npm run db:postgres:deploy && node index.js"]

