/**
 * Stripe webhook receiver. Mounted BEFORE express.json() so the raw bytes
 * survive for HMAC signature verification. Each handler is idempotent on
 * `event.id` via the WebhookEvent table.
 *
 * Generated by platform-generator (Tier 10).
 */
const express = require('express');
const router = express.Router();

const prisma = require('../lib/prisma');
const stripe = require('../lib/billing/stripe');
const dunning = require('../lib/billing/dunning');

router.post(
  '/stripe',
  express.raw({ type: 'application/json', limit: '1mb' }),
  async (req, res) => {
    if (!stripe.isConfigured()) {
      return res.status(503).json({ error: 'billing_not_configured' });
    }

    const sig = req.headers['stripe-signature'];
    let event;
    try {
      event = stripe.verifyWebhook(req.body, sig);
    } catch (err) {
      console.warn(JSON.stringify({ type: 'stripe_webhook_bad_sig', error: err.message }));
      return res.status(400).send(`Webhook Error: ${err.message}`);
    }

    // Idempotency: skip if we've seen this event id before.
    try {
      await prisma.stripeEvent.create({ data: { id: event.id, type: event.type } });
    } catch (err) {
      // Unique violation = duplicate delivery, ack and ignore.
      return res.status(200).json({ received: true, duplicate: true });
    }

    try {
      switch (event.type) {
        case 'customer.subscription.created':
        case 'customer.subscription.updated': {
          const s = event.data.object;
          const orgId = s.metadata?.orgId;
          if (!orgId) break;
          const planId = s.metadata?.tierId || s.items?.data?.[0]?.price?.lookup_key || 'free';
          const status = mapStripeStatus(s.status);
          await prisma.subscription.upsert({
            where: { orgId },
            create: {
              orgId, planId, status,
              stripeSubId: s.id,
              stripeCustomerId: s.customer,
              currentPeriodStart: new Date(s.current_period_start * 1000),
              currentPeriodEnd:   new Date(s.current_period_end   * 1000),
              trialEndsAt: s.trial_end ? new Date(s.trial_end * 1000) : null,
              cancelAt:    s.cancel_at ? new Date(s.cancel_at * 1000) : null,
            },
            update: {
              planId, status,
              stripeSubId: s.id,
              stripeCustomerId: s.customer,
              currentPeriodStart: new Date(s.current_period_start * 1000),
              currentPeriodEnd:   new Date(s.current_period_end   * 1000),
              trialEndsAt: s.trial_end ? new Date(s.trial_end * 1000) : null,
              cancelAt:    s.cancel_at ? new Date(s.cancel_at * 1000) : null,
            },
          });
          break;
        }
        case 'invoice.payment_failed': {
          const inv = event.data.object;
          const orgId = inv.subscription_details?.metadata?.orgId
                     || inv.lines?.data?.[0]?.metadata?.orgId;
          if (orgId) await dunning.markPastDue({ orgId });
          break;
        }
        case 'invoice.payment_succeeded': {
          const inv = event.data.object;
          const orgId = inv.subscription_details?.metadata?.orgId
                     || inv.lines?.data?.[0]?.metadata?.orgId;
          if (orgId) {
            await dunning.activate({
              orgId,
              planId: inv.lines?.data?.[0]?.price?.lookup_key || undefined,
              stripeSubId: inv.subscription,
              currentPeriodStart: new Date(inv.period_start * 1000),
              currentPeriodEnd:   new Date(inv.period_end   * 1000),
            }).catch(() => {});
            // Persist the invoice for the customer's records.
            await prisma.invoice.upsert({
              where: { stripeInvoiceId: inv.id },
              create: {
                stripeInvoiceId: inv.id, orgId,
                amountCents: inv.amount_paid,
                currency: inv.currency,
                status: 'paid',
                periodStart: new Date(inv.period_start * 1000),
                periodEnd:   new Date(inv.period_end   * 1000),
                hostedUrl:   inv.hosted_invoice_url || null,
              },
              update: { status: 'paid', amountCents: inv.amount_paid },
            }).catch(() => {});
          }
          break;
        }
        case 'customer.subscription.deleted': {
          const s = event.data.object;
          const orgId = s.metadata?.orgId;
          if (orgId) await dunning.cancel({ orgId, atPeriodEnd: false });
          break;
        }
        default:
          // Unhandled event types are still acked — Stripe retries 5xx only.
          break;
      }
    } catch (err) {
      console.error(JSON.stringify({
        type: 'stripe_webhook_handler_error',
        eventType: event.type, eventId: event.id, error: err.message,
      }));
      // Return 5xx so Stripe retries with backoff.
      return res.status(500).json({ error: 'handler_failed' });
    }

    return res.status(200).json({ received: true });
  }
);

function mapStripeStatus(s) {
  switch (s) {
    case 'trialing':   return 'trialing';
    case 'active':     return 'active';
    case 'past_due':   return 'past_due';
    case 'unpaid':     return 'grace';
    case 'canceled':   return 'canceled';
    case 'incomplete': return 'past_due';
    case 'incomplete_expired': return 'canceled';
    default:           return 'active';
  }
}

module.exports = router;

