/**
 * Stripe webhook receiver. Mounted BEFORE express.json() so the raw bytes
 * survive for HMAC signature verification. Each handler is idempotent on
 * `event.id` via the WebhookEvent table.
 *
 * Generated by platform-generator (Tier 10).
 */
const express = require('express');
const router = express.Router();

const prisma = require('../lib/prisma');
const stripe = require('../lib/billing/stripe');
const dunning = require('../lib/billing/dunning');
const { runWithSystemAccess } = require('../lib/tenant-context');
const { audit } = require('../lib/audit');

router.post(
  '/stripe',
  express.raw({ type: 'application/json', limit: '1mb' }),
  async (req, res) => {
    if (!stripe.isConfigured()) {
      return res.status(503).json({ error: 'billing_not_configured' });
    }

    const sig = req.headers['stripe-signature'];
    let event;
    try {
      event = stripe.verifyWebhook(req.body, sig);
    } catch (err) {
      console.warn(JSON.stringify({ type: 'stripe_webhook_bad_sig', error: err.message }));
      return res.status(400).send(`Webhook Error: ${err.message}`);
    }

    // Fast-path pre-check only — NOT the authoritative dedup guard (that's
    // the unique constraint inside the transaction below). This just avoids
    // re-running side effects for a delivery we already know succeeded,
    // without an extra round trip for the common case of a first delivery.
    const seen = await prisma.stripeEvent.findUnique({ where: { id: event.id } });
    if (seen) return res.status(200).json({ received: true, duplicate: true });

    // Set inside the transaction below, read after it commits — audit()
    // does its own separate write (not part of `tx`), so it must run only
    // once the state mutation has actually committed, never from inside
    // the transaction callback itself (a later case throwing would roll
    // the mutation back while an audit row for it had already landed).
    let auditInfo = null;

    try {
      // Stripe webhooks aren't tied to any authenticated org's session — the
      // org comes from the event's own metadata, so this is exactly the
      // legitimate, narrow runWithSystemAccess() case lib/tenant-context.js
      // documents (not a per-request org). Without this, every write below
      // ran with NO tenant context at all on real Postgres+RLS: fail-closed
      // RLS makes the target Subscription/Invoice row invisible, so
      // `update()` throws "record not found" and `upsert()` would attempt a
      // spurious `create` that collides with the real (RLS-hidden) row's
      // own unique constraint — every webhook of this kind would 500 on
      // every single delivery, forever, the first time this ran against
      // real production Postgres+RLS.
      //
      // The event-dedup marker is written INSIDE the same transaction as
      // the state mutation (via tenantTransaction — the only primitive that
      // gives real cross-op atomicity under the RLS query-extension; see
      // lib/prisma.js's own comment on why the array `$transaction([...])`
      // form does not). If the mutation throws, the dedup marker rolls back
      // with it, so a genuine Stripe retry can actually reprocess the event
      // instead of being permanently swallowed as "already handled" by a
      // marker written for a delivery that never actually took effect.
      await runWithSystemAccess(async () => {
        await prisma.tenantTransaction(async (tx) => {
          try {
            await tx.stripeEvent.create({ data: { id: event.id, type: event.type } });
          } catch (err) {
            // Only THIS insert's own collision means "genuinely a duplicate
            // delivery" — tagged distinctly so the outer catch doesn't
            // mistake an unrelated P2002 later in this same transaction
            // (e.g. a real Subscription.stripeSubId collision) for a
            // duplicate event and silently ack it instead of letting Stripe
            // retry a mutation that never actually happened.
            if (err && err.code === 'P2002') {
              const dup = new Error('duplicate Stripe event delivery');
              dup.isDuplicateStripeEvent = true;
              throw dup;
            }
            throw err;
          }

          switch (event.type) {
            case 'customer.subscription.created':
            case 'customer.subscription.updated': {
              const s = event.data.object;
              const orgId = s.metadata?.orgId;
              if (!orgId) break;
              const planId = s.metadata?.tierId || s.items?.data?.[0]?.price?.lookup_key || 'free';
              const status = mapStripeStatus(s.status);
              await tx.subscription.upsert({
                where: { orgId },
                create: {
                  orgId, planId, status,
                  stripeSubId: s.id,
                  stripeCustomerId: s.customer,
                  currentPeriodStart: new Date(s.current_period_start * 1000),
                  currentPeriodEnd:   new Date(s.current_period_end   * 1000),
                  trialEndsAt: s.trial_end ? new Date(s.trial_end * 1000) : null,
                  cancelAt:    s.cancel_at ? new Date(s.cancel_at * 1000) : null,
                },
                update: {
                  planId, status,
                  stripeSubId: s.id,
                  stripeCustomerId: s.customer,
                  currentPeriodStart: new Date(s.current_period_start * 1000),
                  currentPeriodEnd:   new Date(s.current_period_end   * 1000),
                  trialEndsAt: s.trial_end ? new Date(s.trial_end * 1000) : null,
                  cancelAt:    s.cancel_at ? new Date(s.cancel_at * 1000) : null,
                },
              });
              auditInfo = { action: 'billing.subscription.upserted', orgId, resource: 'subscription', resourceId: orgId, details: { stripeEventType: event.type, planId, status } };
              break;
            }
            case 'invoice.payment_failed': {
              const inv = event.data.object;
              const orgId = inv.subscription_details?.metadata?.orgId
                         || inv.lines?.data?.[0]?.metadata?.orgId;
              if (orgId) {
                await dunning.markPastDue({ orgId }, tx);
                auditInfo = { action: 'billing.invoice.payment_failed', orgId, resource: 'subscription', resourceId: orgId, details: { stripeInvoiceId: inv.id } };
              }
              break;
            }
            case 'invoice.payment_succeeded': {
              const inv = event.data.object;
              const orgId = inv.subscription_details?.metadata?.orgId
                         || inv.lines?.data?.[0]?.metadata?.orgId;
              if (orgId) {
                // No more .catch(() => {}) here — a real failure must
                // propagate so the transaction rolls back (including the
                // dedup marker above) and Stripe's retry can try again,
                // instead of the failure being silently discarded while the
                // handler still reports success.
                await dunning.activate({
                  orgId,
                  planId: inv.lines?.data?.[0]?.price?.lookup_key || undefined,
                  stripeSubId: inv.subscription,
                  currentPeriodStart: new Date(inv.period_start * 1000),
                  currentPeriodEnd:   new Date(inv.period_end   * 1000),
                }, tx);
                // Persist the invoice for the customer's records.
                await tx.invoice.upsert({
                  where: { stripeInvoiceId: inv.id },
                  create: {
                    stripeInvoiceId: inv.id, orgId,
                    amountCents: inv.amount_paid,
                    currency: inv.currency,
                    status: 'paid',
                    periodStart: new Date(inv.period_start * 1000),
                    periodEnd:   new Date(inv.period_end   * 1000),
                    hostedUrl:   inv.hosted_invoice_url || null,
                  },
                  update: { status: 'paid', amountCents: inv.amount_paid },
                });
                auditInfo = { action: 'billing.invoice.payment_succeeded', orgId, resource: 'invoice', resourceId: inv.id, details: { amountCents: inv.amount_paid } };
              }
              break;
            }
            case 'customer.subscription.deleted': {
              const s = event.data.object;
              const orgId = s.metadata?.orgId;
              if (orgId) {
                await dunning.cancel({ orgId, atPeriodEnd: false }, tx);
                auditInfo = { action: 'billing.subscription.canceled', orgId, resource: 'subscription', resourceId: orgId, details: { stripeSubId: s.id } };
              }
              break;
            }
            default:
              // Unhandled event types are still acked — Stripe retries 5xx only.
              break;
          }
        });
      });
    } catch (err) {
      if (err && err.isDuplicateStripeEvent) {
        // A concurrent delivery of the same event won the race to insert
        // the dedup marker first — genuinely handled (or being handled)
        // elsewhere; ack this one rather than erroring/retrying forever.
        return res.status(200).json({ received: true, duplicate: true });
      }
      console.error(JSON.stringify({
        type: 'stripe_webhook_handler_error',
        eventType: event.type, eventId: event.id, error: err.message,
      }));
      // Return 5xx so Stripe retries with backoff.
      return res.status(500).json({ error: 'handler_failed' });
    }

    // Only now, after the transaction has actually committed — audit() is
    // its own separate write, never part of `tx`, so logging it any
    // earlier could record a mutation that a later case in the switch
    // then rolled back. (audit() always writes under its own system-access
    // grant internally — see lib/audit.js — so no ambient context is
    // needed here even though the outer runWithSystemAccess above has
    // already returned by this point.)
    if (auditInfo) {
      await audit(req, auditInfo.action, { orgId: auditInfo.orgId, resource: auditInfo.resource, resourceId: auditInfo.resourceId, details: auditInfo.details });
    }
    return res.status(200).json({ received: true });
  }
);

function mapStripeStatus(s) {
  switch (s) {
    case 'trialing':   return 'trialing';
    case 'active':     return 'active';
    case 'past_due':   return 'past_due';
    case 'unpaid':     return 'grace';
    case 'canceled':   return 'canceled';
    case 'incomplete': return 'past_due';
    case 'incomplete_expired': return 'canceled';
    default:           return 'active';
  }
}

module.exports = router;

