/**
 * /api/trust/* — public trust portal API.
 *
 *   GET  /api/trust/summary          → JSON posture (no auth)
 *   GET  /api/trust/documents/:name  → individual artifact (no auth)
 *   GET  /api/trust/pack             → compliance-pack.zip download (no auth)
 *
 * No auth on this router by design — vendor risk teams pull these without
 * accounts. Per-org documents (e.g. customer-specific DPA) live elsewhere.
 *
 * Generated by platform-generator (Tier 11).
 */
const express = require('express');
const trust = require('../lib/trust-pack');

const router = express.Router();

router.get('/summary', (req, res) => {
  res.set('Cache-Control', 'public, max-age=300');
  res.json(trust.getPublicSummary());
});

router.get('/documents/:name', (req, res) => {
  const doc = trust.readDocument(req.params.name);
  if (!doc) return res.status(404).json({ error: 'document_not_found' });
  res.set('Content-Type', doc.mime);
  res.set('x-document-sha256', doc.sha256);
  res.set('Cache-Control', 'public, max-age=300');
  return res.send(doc.buffer);
});

router.get('/pack', async (req, res) => {
  try {
    await trust.streamCompliancePack(res);
  } catch (err) {
    if (!res.headersSent) res.status(500).json({ error: err.message });
  }
});

module.exports = router;

