/**
 * Trial / dunning / grace-period state machine. Drives subscription
 * lifecycle transitions independent of Stripe so we still behave
 * sensibly when Stripe is offline or the deployment is self-hosted with
 * a different processor.
 *
 *   trialing  ──(trial_ends && payment_ok)──▶ active
 *   trialing  ──(trial_ends && no payment)──▶ canceled
 *   active    ──(invoice_failed)──▶ past_due
 *   past_due  ──(retry_ok within grace)──▶ active
 *   past_due  ──(grace_expired)──▶ grace
 *   grace     ──(grace_expired_2)──▶ suspended
 *   suspended ──(payment_succeeded)──▶ active
 *
 * Generated by platform-generator (Tier 10).
 */
const prisma = require('../prisma');

const GRACE_DAYS_DEFAULT     = parseInt(process.env.BILLING_GRACE_DAYS     || '7',  10);
const SUSPEND_DAYS_DEFAULT   = parseInt(process.env.BILLING_SUSPEND_DAYS   || '14', 10);
const TRIAL_REMINDER_DAYS    = [3, 1]; // days before trial end to nudge

function addDays(date, days) {
  const d = new Date(date);
  d.setUTCDate(d.getUTCDate() + days);
  return d;
}

/** Called by webhook on `customer.subscription.created` / trial_will_end. */
async function startTrial({ orgId, planId, trialDays, stripeSubId, stripeCustomerId }) {
  const now = new Date();
  const trialEndsAt = addDays(now, trialDays || 14);
  return prisma.subscription.upsert({
    where: { orgId },
    create: {
      orgId, planId,
      status: 'trialing',
      stripeSubId, stripeCustomerId,
      trialEndsAt,
      currentPeriodStart: now,
      currentPeriodEnd: trialEndsAt,
    },
    update: {
      planId, status: 'trialing',
      stripeSubId, stripeCustomerId,
      trialEndsAt,
      currentPeriodStart: now,
      currentPeriodEnd: trialEndsAt,
    },
  });
}

async function activate({ orgId, planId, stripeSubId, currentPeriodStart, currentPeriodEnd }) {
  return prisma.subscription.update({
    where: { orgId },
    data: {
      planId, status: 'active', stripeSubId,
      currentPeriodStart: currentPeriodStart || new Date(),
      currentPeriodEnd:   currentPeriodEnd   || addDays(new Date(), 30),
      pastDueSince: null, graceUntil: null,
    },
  });
}

async function markPastDue({ orgId, graceDays = GRACE_DAYS_DEFAULT }) {
  const now = new Date();
  return prisma.subscription.update({
    where: { orgId },
    data: {
      status: 'past_due',
      pastDueSince: now,
      graceUntil: addDays(now, graceDays),
    },
  });
}

async function markGrace({ orgId, suspendDays = SUSPEND_DAYS_DEFAULT }) {
  const now = new Date();
  return prisma.subscription.update({
    where: { orgId },
    data: { status: 'grace', graceUntil: addDays(now, suspendDays) },
  });
}

async function suspend({ orgId }) {
  return prisma.subscription.update({
    where: { orgId },
    data: { status: 'suspended', suspendedAt: new Date() },
  });
}

async function cancel({ orgId, atPeriodEnd = false }) {
  const sub = await prisma.subscription.findUnique({ where: { orgId } });
  if (!sub) return null;
  return prisma.subscription.update({
    where: { orgId },
    data: {
      status: atPeriodEnd ? sub.status : 'canceled',
      cancelAt: atPeriodEnd ? sub.currentPeriodEnd : new Date(),
      canceledAt: atPeriodEnd ? null : new Date(),
    },
  });
}

/**
 * Sweep — typically run from BullMQ on a 1h schedule. Promotes trials,
 * escalates past-due → grace → suspended, and emits notifications. Idempotent.
 */
async function sweepLifecycles() {
  const now = new Date();
  const counts = { trial_ended: 0, escalated_to_grace: 0, suspended: 0 };

  const expiredTrials = await prisma.subscription.findMany({
    where: { status: 'trialing', trialEndsAt: { lt: now } },
  });
  for (const s of expiredTrials) {
    // No payment method captured → cancel; otherwise activate (Stripe will
    // confirm via webhook anyway, this is the offline fallback).
    if (!s.stripeCustomerId) {
      await cancel({ orgId: s.orgId, atPeriodEnd: false });
    } else {
      await markPastDue({ orgId: s.orgId });
    }
    counts.trial_ended++;
  }

  const pastDueExpired = await prisma.subscription.findMany({
    where: { status: 'past_due', graceUntil: { lt: now } },
  });
  for (const s of pastDueExpired) {
    await markGrace({ orgId: s.orgId });
    counts.escalated_to_grace++;
  }

  const graceExpired = await prisma.subscription.findMany({
    where: { status: 'grace', graceUntil: { lt: now } },
  });
  for (const s of graceExpired) {
    await suspend({ orgId: s.orgId });
    counts.suspended++;
  }

  return counts;
}

module.exports = {
  startTrial, activate, markPastDue, markGrace, suspend, cancel,
  sweepLifecycles, TRIAL_REMINDER_DAYS,
};

