/**
 * Stripe billing adapter — ZERO-config-safe. Loads the Stripe SDK lazily
 * and degrades gracefully when STRIPE_SECRET_KEY is missing (returns null
 * client; routes will respond 503 "billing not configured" instead of
 * crashing the boot). This lets the platform run cleanly in dev / demos
 * with no Stripe account at all.
 *
 * Generated by platform-generator (Tier 10).
 */
let stripeClient = null;
let stripeLoadError = null;

function getStripe() {
  if (stripeClient) return stripeClient;
  if (stripeLoadError) return null;
  const key = process.env.STRIPE_SECRET_KEY;
  if (!key || key === 'sk_test_changeme' || key.length < 20) {
    return null; // not configured
  }
  try {
    const Stripe = require('stripe');
    stripeClient = new Stripe(key, {
      apiVersion: '2024-06-20',
      maxNetworkRetries: 2,
      timeout: 8000,
    });
    return stripeClient;
  } catch (err) {
    stripeLoadError = err;
    console.warn(JSON.stringify({ type: 'stripe_load_failed', error: err.message }));
    return null;
  }
}

function isConfigured() {
  return Boolean(getStripe());
}

/** Create or retrieve a Stripe customer for an organization. */
async function ensureCustomer({ orgId, email, name, metadata = {} }) {
  const s = getStripe();
  if (!s) throw billingNotConfigured();
  const prisma = require('../prisma');
  const existing = await prisma.subscription.findFirst({
    where: { orgId, stripeCustomerId: { not: null } },
    select: { stripeCustomerId: true },
  }).catch(() => null);
  if (existing?.stripeCustomerId) return existing.stripeCustomerId;

  const customer = await s.customers.create({
    email,
    name,
    metadata: { orgId, ...metadata },
  });
  return customer.id;
}

/** Create a Checkout session for a tier + billing cadence. */
async function createCheckoutSession({ orgId, email, name, tierId, cadence = 'monthly', successUrl, cancelUrl }) {
  const s = getStripe();
  if (!s) throw billingNotConfigured();
  const ent = require('../entitlements');
  const tier = ent.getTier(tierId);
  if (!tier) throw new Error(`unknown_tier:${tierId}`);
  const priceId = cadence === 'yearly' ? tier.stripe_price_yearly : tier.stripe_price_monthly;
  if (!priceId) throw new Error(`tier_not_billable:${tierId}:${cadence}`);

  const customerId = await ensureCustomer({ orgId, email, name });
  const trialDays = (tier.trial_days != null) ? tier.trial_days : (ent.PLANS.trial_days_default || 0);

  return s.checkout.sessions.create({
    mode: 'subscription',
    customer: customerId,
    line_items: [{ price: priceId, quantity: 1 }],
    subscription_data: trialDays > 0 ? { trial_period_days: trialDays } : undefined,
    allow_promotion_codes: true,
    success_url: successUrl,
    cancel_url: cancelUrl,
    metadata: { orgId, tierId, cadence },
  });
}

/**
 * One-time Checkout session for a single evidence packet (the $149 SKU).
 *
 * mode:'payment', not 'subscription' — this is deliberately not a plan. Two
 * details matter:
 *
 *  - `invoice_creation: { enabled: true }` makes Stripe issue a real invoice
 *    for the one-off, so it arrives through the SAME
 *    `invoice.payment_succeeded` webhook that subscription revenue uses and
 *    lands in the Invoice table. That keeps one revenue ledger rather than
 *    two, and the Competition Evidence Center's arms-length revenue reporting
 *    picks it up with no extra wiring.
 *  - price_data inline rather than a pre-provisioned Price: the amount is a
 *    single env-tunable number, and requiring `npm run stripe:setup` to have
 *    run first would make this fail closed in exactly the moment it matters
 *    (a contractor with a live dispute, ready to pay).
 */
async function createPacketCheckoutSession({ orgId, email, name, successUrl, cancelUrl, amountCents }) {
  const s = getStripe();
  if (!s) throw billingNotConfigured();
  const credits = require('./packet-credits');
  const unitAmount = amountCents || credits.PACKET_PRICE_CENTS;
  const customerId = await ensureCustomer({ orgId, email, name });

  return s.checkout.sessions.create({
    mode: 'payment',
    customer: customerId,
    line_items: [{
      quantity: 1,
      price_data: {
        currency: 'usd',
        unit_amount: unitAmount,
        product_data: {
          name: 'ScopeCash AI — Evidence Packet',
          description: 'One defensible, citation-backed evidence packet for a single change order or payment dispute. Credited toward a plan if you upgrade within 60 days.',
        },
      },
    }],
    invoice_creation: { enabled: true },
    allow_promotion_codes: true,
    success_url: successUrl,
    cancel_url: cancelUrl,
    // orgId is what the webhook uses to attribute the credit — without it a
    // completed payment cannot be tied back to a tenant.
    metadata: { orgId, sku: 'evidence_packet' },
  });
}

/** Customer Portal session for self-service plan changes / payment methods. */
async function createPortalSession({ orgId, returnUrl }) {
  const s = getStripe();
  if (!s) throw billingNotConfigured();
  const prisma = require('../prisma');
  const sub = await prisma.subscription.findFirst({
    where: { orgId, stripeCustomerId: { not: null } },
    orderBy: { createdAt: 'desc' },
  });
  if (!sub?.stripeCustomerId) throw new Error('no_customer');
  return s.billingPortal.sessions.create({
    customer: sub.stripeCustomerId,
    return_url: returnUrl,
  });
}

/**
 * Verify a Stripe webhook signature against the raw request body.
 * Returns the parsed Event or throws on tamper / bad secret.
 */
function verifyWebhook(rawBody, signature) {
  const s = getStripe();
  if (!s) throw billingNotConfigured();
  const secret = process.env.STRIPE_WEBHOOK_SECRET;
  if (!secret) throw new Error('webhook_secret_missing');
  return s.webhooks.constructEvent(rawBody, signature, secret);
}

/**
 * Push a metered usage record to a Stripe subscription item. Best-effort —
 * caller already persisted the event locally. Quietly skips when Stripe
 * is not configured or when the meter has no Stripe item id mapped.
 */
async function reportMeteredUsage({ stripeSubItemId, quantity, idempotencyKey }) {
  // DEPRECATED and now inert by design. subscriptionItems.createUsageRecord
  // was removed in Stripe SDK v22 (this repo runs 22.3.2 — the property is
  // `undefined`), so this used to throw "not a function" at every caller.
  // Kept as an explicit, loud no-op rather than deleted because its only
  // caller (jobs/usage-aggregator.js#reportMeteredUsageToStripe) is itself a
  // documented skeleton; deleting it would silently change that file's shape.
  // Use reportMeterEvent below.
  console.warn(JSON.stringify({
    severity: 'WARNING', type: 'stripe_deprecated_usage_record_call',
    note: 'subscriptionItems.createUsageRecord no longer exists in Stripe v22; use reportMeterEvent',
    stripeSubItemId, quantity, idempotencyKey,
  }));
  return { sent: false, reason: 'deprecated_api_removed_in_stripe_v22' };
}

/**
 * Report a usage event via Stripe's Meter Events API — the supported
 * replacement for createUsageRecord.
 *
 * `identifier` is Stripe's own dedup key for meter events: replaying the same
 * identifier does not double-count, which is what makes this safe to call
 * from a retried job or a redelivered webhook.
 */
async function reportMeterEvent({ eventName, stripeCustomerId, quantity = 1, identifier }) {
  const s = getStripe();
  if (!s) return { sent: false, reason: 'stripe_unconfigured' };
  if (!eventName || !stripeCustomerId) return { sent: false, reason: 'missing_meter_or_customer' };

  await s.billing.meterEvents.create({
    event_name: eventName,
    identifier,
    payload: {
      // Stripe requires these as strings on the payload.
      stripe_customer_id: String(stripeCustomerId),
      value: String(quantity),
    },
  });
  return { sent: true, reported: true, eventName, identifier };
}

function billingNotConfigured() {
  const e = new Error('billing_not_configured');
  e.code = 'billing_not_configured';
  e.statusCode = 503;
  return e;
}

module.exports = {
  isConfigured,
  ensureCustomer,
  createCheckoutSession,
  createPacketCheckoutSession,
  createPortalSession,
  verifyWebhook,
  reportMeteredUsage,
  reportMeterEvent,
};

