/**
 * Entitlements middleware — drop-in Express guards for feature flags and
 * usage meters. Use as `router.post('/x', requireFeature('sso'), ...)` or
 * `router.post('/y', enforceMeter('records_per_month'), ...)`.
 *
 * Resolves the org from req.user.orgId (set by authMiddleware). Returns
 * 402 Payment Required (RFC 7231 §6.5.2 — semantically correct for "need
 * to upgrade") with structured upgrade hints.
 *
 * Generated by platform-generator (Tier 10).
 */
const ent = require('../lib/entitlements');
const meter = require('../lib/usage-meter');

// req.tenant.orgId is the canonical resolved org (middleware/tenant.js
// falls back to req.user.id when req.user.orgId is unset — a route that
// ran attachTenant, which enforceMeter/requireFeature require to mean
// anything, always has this set). Falls back to the raw req.user.orgId
// for defensiveness only, e.g. a route that hasn't run attachTenant yet.
function _orgIdFromReq(req) {
  return req.tenant?.orgId || req.user?.orgId || null;
}

function requireFeature(feature) {
  return async (req, res, next) => {
    try {
      const orgId = _orgIdFromReq(req);
      const allowed = await ent.can(orgId, feature);
      if (!allowed) {
        const message = `The "${feature}" feature is not included in your current plan.`;
        return res.status(402).json({
          // `error` holds the human-readable message (not the code) to
          // match this codebase's own convention (lib/validate.js's
          // HttpError/errorMiddleware) — apiJson on the dashboard reads
          // body.error first, so a code string here would show the user
          // literally "feature_not_in_plan" instead of a real sentence.
          error: message, code: 'feature_not_in_plan', message,
          feature, upgrade_url: '/settings/billing', requestId: req.requestId,
        });
      }
      return next();
    } catch (err) { return next(err); }
  };
}

/**
 * enforceMeter — checks remaining quota BEFORE the handler runs and (if
 * `recordOnSuccess` is true, the default) records `quantity` usage when
 * the response completes 2xx. For pre-flight only, set { record:false }.
 */
function enforceMeter(meterName, opts = {}) {
  const { quantity = 1, record = true, allowOverage = false } = opts;
  return async (req, res, next) => {
    try {
      const orgId = _orgIdFromReq(req);
      const qty = typeof quantity === 'function' ? Number(quantity(req)) || 1 : quantity;
      // req.tenant.plan is the tier attachTenant already resolved for this
      // request — passing it avoids checkUsage() re-querying Subscription.
      const status = await ent.checkUsage(orgId, meterName, qty, req.tenant?.plan);

      if (!status.allowed && !allowOverage) {
        const message = `Monthly limit reached for ${meterName} (${status.used}/${status.limit}).`;
        return res.status(402).json({
          error: message, code: 'usage_limit_exceeded', message,
          meter: meterName, used: status.used, limit: status.limit, remaining: status.remaining,
          upgrade_url: '/settings/billing', requestId: req.requestId,
        });
      }

      // Hint headers — opt-in observability for clients that care
      if (status.limit !== -1) {
        res.setHeader('x-quota-meter', meterName);
        res.setHeader('x-quota-used', String(status.used));
        res.setHeader('x-quota-limit', String(status.limit));
        res.setHeader('x-quota-remaining', String(status.remaining));
      }

      if (record) {
        res.on('finish', () => {
          if (res.statusCode >= 200 && res.statusCode < 300) {
            meter.recordUsage({
              orgId,
              userId: req.user?.id,
              meter: meterName,
              quantity: qty,
              metadata: { route: req.originalUrl, method: req.method, requestId: req.requestId },
            }).catch(() => {});
          }
        });
      }
      return next();
    } catch (err) { return next(err); }
  };
}

/**
 * Block all writes when the subscription is in `suspended` status. Reads
 * stay open so customers can export their data after non-payment.
 */
function blockIfSuspended() {
  return async (req, res, next) => {
    try {
      if (['GET', 'HEAD', 'OPTIONS'].includes(req.method)) return next();
      const orgId = _orgIdFromReq(req);
      if (!orgId) return next();
      const sub = await ent.getActiveSubscription(orgId);
      if (sub.status === 'suspended') {
        const message = 'Your subscription is suspended for non-payment. Reads are still allowed; please update billing to restore writes.';
        return res.status(402).json({
          error: message, code: 'subscription_suspended', message,
          upgrade_url: '/settings/billing', requestId: req.requestId,
        });
      }
      return next();
    } catch (err) { return next(err); }
  };
}

module.exports = { requireFeature, enforceMeter, blockIfSuspended };

