/**
 * Entitlements middleware — drop-in Express guards for feature flags and
 * usage meters. Use as `router.post('/x', requireFeature('sso'), ...)` or
 * `router.post('/y', enforceMeter('records_per_month'), ...)`.
 *
 * Resolves the org from req.user.orgId (set by authMiddleware). Returns
 * 402 Payment Required (RFC 7231 §6.5.2 — semantically correct for "need
 * to upgrade") with structured upgrade hints.
 *
 * Generated by platform-generator (Tier 10).
 */
const ent = require('../lib/entitlements');
const meter = require('../lib/usage-meter');

function _orgIdFromReq(req) {
  return req.user?.orgId || req.org?.id || null;
}

function requireFeature(feature) {
  return async (req, res, next) => {
    try {
      const orgId = _orgIdFromReq(req);
      const allowed = await ent.can(orgId, feature);
      if (!allowed) {
        return res.status(402).json({
          error: 'feature_not_in_plan',
          code: 'feature_not_in_plan',
          feature,
          message: `The "${feature}" feature is not included in your current plan.`,
          upgrade_url: '/settings/billing',
          requestId: req.requestId,
        });
      }
      return next();
    } catch (err) { return next(err); }
  };
}

/**
 * enforceMeter — checks remaining quota BEFORE the handler runs and (if
 * `recordOnSuccess` is true, the default) records `quantity` usage when
 * the response completes 2xx. For pre-flight only, set { record:false }.
 */
function enforceMeter(meterName, opts = {}) {
  const { quantity = 1, record = true, allowOverage = false } = opts;
  return async (req, res, next) => {
    try {
      const orgId = _orgIdFromReq(req);
      const qty = typeof quantity === 'function' ? Number(quantity(req)) || 1 : quantity;
      const status = await ent.checkUsage(orgId, meterName, qty);

      if (!status.allowed && !allowOverage) {
        return res.status(402).json({
          error: 'usage_limit_exceeded',
          code: 'usage_limit_exceeded',
          meter: meterName,
          used: status.used,
          limit: status.limit,
          remaining: status.remaining,
          message: `Monthly limit reached for ${meterName} (${status.used}/${status.limit}).`,
          upgrade_url: '/settings/billing',
          requestId: req.requestId,
        });
      }

      // Hint headers — opt-in observability for clients that care
      if (status.limit !== -1) {
        res.setHeader('x-quota-meter', meterName);
        res.setHeader('x-quota-used', String(status.used));
        res.setHeader('x-quota-limit', String(status.limit));
        res.setHeader('x-quota-remaining', String(status.remaining));
      }

      if (record) {
        res.on('finish', () => {
          if (res.statusCode >= 200 && res.statusCode < 300) {
            meter.recordUsage({
              orgId,
              userId: req.user?.id,
              meter: meterName,
              quantity: qty,
              metadata: { route: req.originalUrl, method: req.method, requestId: req.requestId },
            }).catch(() => {});
          }
        });
      }
      return next();
    } catch (err) { return next(err); }
  };
}

/**
 * Block all writes when the subscription is in `suspended` status. Reads
 * stay open so customers can export their data after non-payment.
 */
function blockIfSuspended() {
  return async (req, res, next) => {
    try {
      if (['GET', 'HEAD', 'OPTIONS'].includes(req.method)) return next();
      const orgId = _orgIdFromReq(req);
      if (!orgId) return next();
      const sub = await ent.getActiveSubscription(orgId);
      if (sub.status === 'suspended') {
        return res.status(402).json({
          error: 'subscription_suspended',
          code: 'subscription_suspended',
          message: 'Your subscription is suspended for non-payment. Reads are still allowed; please update billing to restore writes.',
          upgrade_url: '/settings/billing',
          requestId: req.requestId,
        });
      }
      return next();
    } catch (err) { return next(err); }
  };
}

module.exports = { requireFeature, enforceMeter, blockIfSuspended };

