/**
 * Plan → execution lane mapping (Tier 12 — Multi-tenant economics).
 *
 * Lanes provide noisy-neighbor isolation: free/starter share a low-priority
 * pool, pro gets mid-priority, enterprise gets a dedicated worker / highest
 * priority. Used by:
 *   - BullMQ job priority (lower number = higher priority)
 *   - Per-tenant rate limit ceilings
 *   - Per-tenant connection pool budgets
 *
 * Generated by platform-generator for industry=home-services.
 */

// Lower priority value = served sooner in BullMQ
const LANES = Object.freeze({
  'shared-low':   { priority: 100, maxConcurrent: 2, dbBudget: 10, label: 'shared-low'  },
  'shared-mid':   { priority: 50,  maxConcurrent: 5, dbBudget: 25, label: 'shared-mid'  },
  'shared-high':  { priority: 20,  maxConcurrent: 12, dbBudget: 50, label: 'shared-high' },
  'dedicated':    { priority: 5,   maxConcurrent: 50, dbBudget: 200, label: 'dedicated' },
});

// Default per-plan lane assignment. Industry overlays may override via env.
const DEFAULT_PLAN_LANE = Object.freeze({
  free:       'shared-low',
  starter:    'shared-mid',
  pro:        'shared-high',
  enterprise: 'dedicated',
});

function laneForPlan(planId) {
  if (!planId) return LANES['shared-low'];
  // Allow per-deployment override: TENANT_LANE_<PLAN>=dedicated
  const envKey = `TENANT_LANE_${String(planId).toUpperCase()}`;
  const override = process.env[envKey];
  const name = (override && LANES[override]) ? override : (DEFAULT_PLAN_LANE[planId] || 'shared-low');
  return LANES[name];
}

/** Per-minute request ceiling for a plan. Enforced by ratelimit.perTenant(). */
function rateBudgetForPlan(planId) {
  // Ceilings should be lower than infrastructure capacity but high enough
  // for real workloads. Tuned for a single mid-tier API node.
  const TABLE = {
    free:        60,
    starter:    300,
    pro:       1200,
    enterprise: 6000,
  };
  return TABLE[planId] || TABLE.free;
}

/** AI-token-per-minute ceiling per tenant (sub-ceiling under entitlements). */
function aiBudgetForPlan(planId) {
  const TABLE = {
    free:         2_000,
    starter:     20_000,
    pro:        200_000,
    enterprise:1_000_000,
  };
  return TABLE[planId] || TABLE.free;
}

module.exports = {
  LANES,
  laneForPlan,
  rateBudgetForPlan,
  aiBudgetForPlan,
};

