/**
 * Trust artifact registry — exposes the platform's security & compliance
 * posture as both a public JSON document (for vendor questionnaires) and
 * a downloadable compliance pack (ZIP) for procurement teams.
 *
 * The pack contents are all generated, version-controlled artifacts; nothing
 * is fetched from external services at request time. Customers can sha256
 * the ZIP and pin it in their vendor risk file.
 *
 * Generated by platform-generator (Tier 11 — Trust Artifacts).
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const archiver = require('archiver');

const TRUST_ROOT = path.join(__dirname, '..', 'trust');
const PACKAGE_VERSION = require('../package.json').version;

// Explicit, operator-set data-residency region for this deployment — see
// DEPLOY.md and trust/ropa-template.md's "Hosted in the US by default
// (region configurable per deployment)". This used to be a hardcoded
// `['US', 'EU']` literal in the summary below, unconditionally claiming
// BOTH regions were simultaneously available in the public trust portal
// (served unauthenticated, exactly what a vendor-risk team pulls to decide
// whether to trust this vendor with their data) — but the actual
// architecture is single-region-per-deployment with no per-customer region
// choice anywhere in the product. Reading it from an env var instead makes
// the claim track whatever region the deployment was actually configured
// for, cloud-agnostic (works the same whether the operator set GCP's
// `region`, AWS's `region`, or Fly's `primary_region` in their own deploy
// config) — defaults to 'US' to match the already-corrected ropa-template.
const DATA_RESIDENCY_REGION = process.env.DATA_RESIDENCY_REGION || 'US';

let _summaryCache = null;

/** Public trust posture summary. Safe to expose unauthenticated. */
function getPublicSummary() {
  if (_summaryCache) return _summaryCache;

  const subprocessors = readJsonSafe('subprocessors.json', { subprocessors: [] });
  const compliance = readJsonSafe('compliance.json', { frameworks: [] });
  const security = readJsonSafe('security-controls.json', { controls: [] });
  const retention = readJsonSafe('retention-schedule.json', { retention: [] });

  _summaryCache = {
    platform: 'ScopeCash AI',
    industry: 'home-services',
    version: PACKAGE_VERSION,
    generatedAt: new Date().toISOString(),
    compliance: {
      frameworks: compliance.frameworks || [],
      attested: compliance.attested || false,
      last_audit_date: compliance.last_audit_date || null,
      next_audit_date: compliance.next_audit_date || null,
    },
    security: {
      controls_count: (security.controls || []).length,
      encryption_in_transit: 'TLS 1.2+',
      encryption_at_rest:    'AES-256',
      mfa_supported:         true,
      sso_supported:         true,
      audit_log:             true,
      data_residency:        [DATA_RESIDENCY_REGION],
      sbom:                  'CycloneDX/SPDX, signed via cosign keyless (sigstore)',
      attestations:          ['SLSA Build L3 (provenance)', 'SBOM attestation (cosign)'],
    },
    subprocessors: {
      count: (subprocessors.subprocessors || []).length,
      list:  subprocessors.subprocessors || [],
    },
    data_handling: {
      retention_policies: retention.retention || [],
      deletion_sla_days:  30,
      export_formats:     ['JSON', 'CSV'],
      gdpr_dsr_endpoint:  '/api/privacy/dsr',
    },
    incident_response: {
      notification_sla_hours: 72,
      contact: 'security@scopecash-ai.example',
    },
    documents: listAvailableDocuments(),
  };
  return _summaryCache;
}

function readJsonSafe(name, fallback) {
  try {
    const p = path.join(TRUST_ROOT, name);
    if (!fs.existsSync(p)) return fallback;
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch { return fallback; }
}

/** List documents under server/trust/ for the pack manifest. */
function listAvailableDocuments() {
  if (!fs.existsSync(TRUST_ROOT)) return [];
  return fs.readdirSync(TRUST_ROOT)
    .filter(f => !f.startsWith('.') && fs.statSync(path.join(TRUST_ROOT, f)).isFile())
    .map(name => {
      const full = path.join(TRUST_ROOT, name);
      const buf = fs.readFileSync(full);
      return {
        name,
        size_bytes: buf.length,
        sha256: crypto.createHash('sha256').update(buf).digest('hex'),
        mime: guessMime(name),
      };
    });
}

function guessMime(name) {
  if (name.endsWith('.json')) return 'application/json';
  if (name.endsWith('.md'))   return 'text/markdown';
  if (name.endsWith('.pdf'))  return 'application/pdf';
  if (name.endsWith('.txt'))  return 'text/plain';
  return 'application/octet-stream';
}

/** Read a single document by filename — returns { buffer, mime, sha256 } or null. */
function readDocument(name) {
  // Hard guard against path traversal.
  if (!/^[\w.\-]+\.(json|md|pdf|txt)$/.test(name)) return null;
  const full = path.join(TRUST_ROOT, name);
  if (!full.startsWith(TRUST_ROOT)) return null;
  if (!fs.existsSync(full)) return null;
  const buffer = fs.readFileSync(full);
  return {
    buffer,
    mime: guessMime(name),
    sha256: crypto.createHash('sha256').update(buffer).digest('hex'),
  };
}

/** Stream a ZIP of every trust document plus a manifest.json with hashes. */
function streamCompliancePack(res) {
  const archive = archiver('zip', { zlib: { level: 9 } });
  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', 'attachment; filename="compliance-pack.zip"');
  archive.on('error', err => res.status(500).end(`pack error: ${err.message}`));
  archive.pipe(res);

  const summary = getPublicSummary();
  archive.append(JSON.stringify(summary, null, 2), { name: 'TRUST-SUMMARY.json' });
  archive.append(buildReadme(summary), { name: 'README.md' });

  const docs = summary.documents;
  for (const d of docs) {
    archive.file(path.join(TRUST_ROOT, d.name), { name: `documents/${d.name}` });
  }
  archive.append(JSON.stringify({ documents: docs, generatedAt: summary.generatedAt }, null, 2),
                 { name: 'MANIFEST.json' });
  return archive.finalize();
}

function buildReadme(summary) {
  return [
    `# ScopeCash AI — Compliance Pack`,
    ``,
    `Generated: ${summary.generatedAt}`,
    `Platform version: ${summary.version}`,
    ``,
    `## Frameworks`,
    ...summary.compliance.frameworks.map(f => `- ${f}`),
    ``,
    `## Subprocessors`,
    ...summary.subprocessors.list.map(s => `- **${s.name}** (${s.purpose}) — ${s.location}`),
    ``,
    `## Documents`,
    ...summary.documents.map(d => `- \`documents/${d.name}\` (${d.size_bytes} bytes, sha256:${d.sha256})`),
    ``,
    `Verify each document with:`,
    '```sh',
    `sha256sum documents/<file>`,
    '```',
    ``,
  ].join('\n');
}

module.exports = {
  getPublicSummary,
  listAvailableDocuments,
  readDocument,
  streamCompliancePack,
};

