/**
 * Usage meter — append-only event log + monthly counter rollup. Designed
 * to survive bursts (events go in fast) while keeping enforcement cheap
 * (counters are O(1) lookups). The aggregator job reconciles drift and
 * reports overage to Stripe.
 *
 * Generated by platform-generator (Tier 10).
 */
const prisma = require('./prisma');
const ent = require('./entitlements');

/**
 * Record N units of usage for a billable meter. Updates the period counter
 * atomically (upsert + increment) and writes an immutable event row for
 * audit and replay. Never throws into the caller's request path — instead
 * logs and returns { ok:false }.
 */
async function recordUsage({ orgId, userId, meter, quantity = 1, metadata = null, period: explicitPeriod = null }) {
  if (!orgId || !meter || !Number.isFinite(Number(quantity))) {
    return { ok: false, reason: 'invalid_args' };
  }
  const qty = Math.max(0, Math.floor(Number(quantity)));
  if (qty === 0) return { ok: true, recorded: 0 };

  // `period` is normally now, but a buffered caller (lib/api-call-meter.js)
  // must be able to attribute units to the period they were *incurred* in —
  // otherwise traffic just before a month boundary lands on the next month's
  // counter when the flush happens to cross midnight UTC.
  const period = explicitPeriod || ent.currentPeriodKey();
  try {
    await prisma.$transaction([
      prisma.usageEvent.create({
        data: {
          orgId,
          userId: userId || null,
          meter,
          quantity: qty,
          period,
          metadata: metadata ? JSON.stringify(metadata) : null,
        },
      }),
      prisma.usageCounter.upsert({
        where: { orgId_meter_period: { orgId, meter, period } },
        create: { orgId, meter, period, value: qty },
        update: { value: { increment: qty } },
      }),
    ]);
    return { ok: true, recorded: qty, period };
  } catch (err) {
    console.error(JSON.stringify({
      type: 'usage_meter_error',
      orgId, meter, qty, error: err.message,
    }));
    return { ok: false, reason: 'persistence_error' };
  }
}

async function getUsage(orgId, meter, period) {
  const p = period || ent.currentPeriodKey();
  const c = await prisma.usageCounter.findUnique({
    where: { orgId_meter_period: { orgId, meter, period: p } },
  }).catch(() => null);
  return c ? Number(c.value) : 0;
}

async function getAllUsage(orgId, period) {
  const p = period || ent.currentPeriodKey();
  const rows = await prisma.usageCounter.findMany({
    where: { orgId, period: p },
  }).catch(() => []);
  const out = {};
  for (const r of rows) out[r.meter] = Number(r.value);
  return out;
}

module.exports = { recordUsage, getUsage, getAllUsage };

